import 'package:cloud_firestore/cloud_firestore.dart';

import '../models/widow/widow.dart';

class DatabaseService {
  final String akokoNorthEast = 'Akoko North East';
  final String akokoSouthEast = 'Akoko South East';
  final String akokoNorthWest = 'Akoko North West';
  final String owo = 'Owo';

  int oneChild = 0;
  int twoChildren = 0;
  int threeChildren = 0;
  int fourChildren = 0;
  int fiveChildren = 0;
  int sixChildren = 0;
  int sevenChildrenPlus = 0;

  int _akokoNorthEastTotal = 0;
  int _owoTotal = 0;
  int _akokoSouthEastTotal = 0;
  int _akokoNorthWestTotal = 0;

  int get owoTotal => _owoTotal;
  int get akokoNorthEastTotal => _akokoNorthEastTotal;
  int get akokoSouthEastTotal => _akokoSouthEastTotal;
  int get akokoNorthWestTotal => _akokoNorthWestTotal;

  // final _store = FirebaseFirestore.instance;
  final String widowsCollectionPath = "Widows";
  late final CollectionReference widowsCollection;

  // Future< QuerySnapshot<Map<String, dynamic>>> getWidowsCollection() async{//todo: Check here.
  //    return await _store.collection(widowsCollectionPath).get();
  //  }

  void _getLGData() {
    for (var i in demoData) {
      if (i.lga == owo) {
        _owoTotal++;
      } else if (i.lga == akokoNorthEast) {
        _akokoNorthEastTotal++;
      } else if (i.lga == akokoNorthWest) {
        _akokoNorthWestTotal++;
      } else if (i.lga == akokoSouthEast) {
        _akokoSouthEastTotal++;
      } else {
        return;
      }
    }
  }

  void _getChildrenData() {
    for (var i in demoData) {
      if (i.numberOfChildren == 1) {
        oneChild++;
      } else if (i.numberOfChildren == 2) {
        twoChildren++;
      } else if (i.numberOfChildren == 3) {
        threeChildren++;
      } else if (i.numberOfChildren == 4) {
        fourChildren++;
      } else if (i.numberOfChildren == 5) {
        fiveChildren++;
      } else if (i.numberOfChildren == 6) {
        sixChildren++;
      } else {
        sevenChildrenPlus++;
      }
    }
  }
}

List<Widow> demoData = [
  Widow(
      id: "ANE000082",
      fullName: "Jayeola Idayat",
      dob: DateTime.parse("1974-01-01 00:00:00.000"),
      state: "Ondo",
      homeTown: "Ikare",
      address: "L/10 Bankole Street",
      lga: "Akoko North East",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07010870233",
      husbandName: "Busiyi Jayeola",
      husbandBereavementDate: "09 May, 2017",
      husbandOccupation: "Skilled Manual Labour (Tailoring, Hairdressing etc)",
      yearOfMarriage: 2007,
      numberOfChildren: 5,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: null,
      accountName: null,
      bankName: null,
      ngoMembership: " NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse('2020-01-30 00:00:00.000'),
      oneOrTwo: null),
  Widow(
      id: "ANE000010",
      fullName: "Yemisi Sulaiman",
      dob: DateTime.parse("1940-01-09 00:00:00.000"),
      state: "Ondo",
      homeTown: "Ikare Akoko",
      address: "1A/15, Odoruwa Street, Ikare Akoko",
      lga: "Owo",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Unemployed",
      phoneNumber: "07016683844",
      husbandName: "Asimi Sulaiman",
      husbandBereavementDate: "04 March, 2017",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1968,
      numberOfChildren: 8,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: null,
      accountName: null,
      bankName: null,
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "None",
      registrationDate: DateTime.parse('2020-01-25 00:00:00.000'),
      oneOrTwo: null),
  Widow(
      id: "ANE000715",
      fullName: "JIMOH ASHAHU",
      dob: DateTime.parse("1952-01-03 00:00:00.000"),
      state: "Kogi",
      homeTown: "OWO",
      address: "OKE IJEBU NO 2",
      lga: "Akoko North East",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07025131747",
      husbandName: "JIMOH ISMAILA",
      husbandBereavementDate: "02 May, 1972",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1952,
      numberOfChildren: 7,
      senatorialZone: " Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: "3048958635",
      accountName: "JIMOH FATAI ENIOLA",
      bankName: "POLARIS",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "P",
      registrationDate: DateTime.parse("2020-01-01 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000811",
      fullName: "ADENOLA ABEKE SIFAU",
      dob: DateTime.parse("1945-01-01 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "K/81 OYINMO STREET IKARE AKOKO",
      lga: "Akoko North West",
      occupation: "Agriculture (Farming, Poultry etc.)",
      employmentStatus: "Unemployed",
      phoneNumber: "07025202860",
      husbandName: "ADENOLA MOMODU",
      husbandBereavementDate: "05 August, 2005",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1970,
      numberOfChildren: 5,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 4",
      accountNumber: "2368913756",
      accountName: "ADENOLA ABEKE SIFAU",
      bankName: "ZENITH BANK",
      ngoMembership: " NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-21 00:00:00.000"),
      oneOrTwo: 1),
  Widow(
      id: "ANE000117",
      fullName: "Osene Kemi Favour",
      dob: DateTime.parse("1987-01-23 00:00:00.000"),
      state: "Ondo",
      homeTown: "Ikare Akoko",
      address: "29c,housing estate,peace garden",
      lga: "Akoko North West",
      occupation: "What is you occupation",
      employmentStatus: "Unemployed",
      phoneNumber: "07026702354",
      husbandName: "Osene Yusuf",
      husbandBereavementDate: "23 December, 2017",
      husbandOccupation: "Sales and Services (Trading)",
      yearOfMarriage: 2008,
      numberOfChildren: 2,
      senatorialZone: " Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 5",
      accountNumber: null,
      accountName: null,
      bankName: null,
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-03 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000776",
      fullName: "Ayodele Janet",
      dob: DateTime.parse("1955-01-18 00:00:00.000"),
      state: "Ondo",
      homeTown: "Erusu Akoko ",
      address: "No 2 Adesola street, Akure high school, Akure",
      lga: "Owo",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Unemployed",
      phoneNumber: "07030067213",
      husbandName: "Oba Moses",
      husbandBereavementDate: "03 May, 2012",
      husbandOccupation:
          "Professional/technical/managerial (Lawyer, Manager, Engineer etc.)",
      yearOfMarriage: 1979,
      numberOfChildren: 6,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: "1902891609",
      accountName: "Ayodele Janet",
      bankName: "Heritage bank",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-10 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000806",
      fullName: "ALETILE AYISAT",
      dob: DateTime.parse("1943-01-01 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "K/74 OYINMO STREET IKARE AKOKO",
      lga: "Akoko North East",
      occupation: "Agriculture (Farming, Poultry etc.)",
      employmentStatus: "Unemployed",
      phoneNumber: "07030073240",
      husbandName: "ALETILE UNISA",
      husbandBereavementDate: "17 September, 2017",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1965,
      numberOfChildren: 4,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 4",
      accountNumber: "2368908709",
      accountName: "ALETILE AYISAT",
      bankName: "ZENITH BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-21 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000480",
      fullName: "OLOGBOGI RAMOTA",
      dob: DateTime.parse("1960-01-21 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "D/30A OKORUN STREET IKARE AKOKO",
      lga: "Akoko North West",
      occupation: "Sales and Ser vices (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07030099717",
      husbandName: "FASASI OLUGBOGI",
      husbandBereavementDate: "02 September, 2000",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1980,
      numberOfChildren: 6,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: " Level 3",
      accountNumber: "6005231047",
      accountName: "OLUGBOGI RAMOTA",
      bankName: "KEYSTONE BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-17 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000637",
      fullName: "Adubiaro abiola",
      dob: DateTime.parse("1977-01-10 00:00:00.000"),
      state: "Ondo",
      homeTown: "Ondo state ",
      address: "No 10 commercial street oke aro",
      lga: "Akoko North East",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07030101376",
      husbandName: "Adubiaro tope",
      husbandBereavementDate: "14 January, 2010",
      husbandOccupation: "Sales and Services (Trading)",
      yearOfMarriage: 1999,
      numberOfChildren: 3,
      senatorialZone: " Ondo North Senatorial District",
      categoryBasedOnNeeds: " Level 3",
      accountNumber: "3021943056",
      accountName: "Adubiaro abiola",
      bankName: "Polaris bank",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-28 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000173",
      fullName: "AGUNBIADE CAROLINE",
      dob: DateTime.parse("1967-01-01 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "IKARA AKOKO",
      lga: "Owo",
      occupation: "Clerical (Administrative, secretarial etc.)",
      employmentStatus: "Employed",
      phoneNumber: "07030103242",
      husbandName: "AGUNBIADE BANKOLE",
      husbandBereavementDate: "21 October, 2019",
      husbandOccupation: "Skilled Manual Labour (Tailoring, Hairdressing etc)",
      yearOfMarriage: 1998,
      numberOfChildren: 3,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 2",
      accountNumber: "2001687808",
      accountName: "AGUNBIADE CAROLINE",
      bankName: "FIRST BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-22 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000517",
      fullName: "OGUNROTIFA VICTORIA",
      dob: DateTime.parse("1958-01-11 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE",
      address: "c/107A Ese stree ikare akoko",
      lga: "Akoko North West",
      occupation: "Clerical (Administrative, secretarial etc.)",
      employmentStatus: "Self Employed",
      phoneNumber: "07030154578",
      husbandName: "MR OGUNROTIFA",
      husbandBereavementDate: "23 December, 2003",
      husbandOccupation:
          "Professional/technical/managerial (Lawyer, Manager, Engineer etc.)",
      yearOfMarriage: 1982,
      numberOfChildren: 3,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: " Level 2",
      accountNumber: "1910273226",
      accountName: "OGUNROTIFA VICTORIA OLUYEMI",
      bankName: "HERITAGE BANK",
      ngoMembership: " NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-18 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000159",
      fullName: "AROWOLO KEMISOLA SELIMO",
      dob: DateTime.parse("1986-01-09 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "H/14M OKERUWA IKARE",
      lga: "Akoko South East",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07030175657",
      husbandName: "AROWOLO BELLO",
      husbandBereavementDate: "21 January, 2016",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 2007,
      numberOfChildren: 3,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: " Level 3",
      accountNumber: "3058795094",
      accountName: "AROWOLO KEMISOLA SELIMO",
      bankName: "FIRST BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-22 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000304",
      fullName: "OSHODI TAIBAT OLANIKE",
      dob: DateTime.parse("1972-01-05 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "L/52B ILEPA IKARE AKOKO",
      lga: "Akoko South East",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07030228892",
      husbandName: "OSHODI NURENI ADEDAYO",
      husbandBereavementDate: "12 September, 2013",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1994,
      numberOfChildren: 5,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: "1910161524",
      accountName: "OSHODI TAIBAT OLANIKE",
      bankName: "HERITAGE BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-11 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000222",
      fullName: "ADU OSEYEMI",
      dob: DateTime.parse("1970-01-10 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "L/NC UDOR STREET ALAPATA IKARE AKOKO",
      lga: "Owo",
      occupation: "Agriculture (Farming, Poultry etc.)",
      employmentStatus: "Self Employed",
      phoneNumber: "07030502643",
      husbandName: "ADU ABIFADE",
      husbandBereavementDate: "04 May, 1998",
      husbandOccupation: "Sales and Services (Trading)",
      yearOfMarriage: 1988,
      numberOfChildren: 4,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 4",
      accountNumber: "3025258117",
      accountName: "ADU OSEYEMI",
      bankName: "FIRST BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-11 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000289",
      fullName: "ALOKO MERCY KIKELOMO",
      dob: DateTime.parse("1983-01-13 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "NEW IYAME QUARTERS IKARE AKOKO",
      lga: "Akoko South East",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07030832124",
      husbandName: "ALOKO JALESANMI",
      husbandBereavementDate: "18 February, 2020",
      husbandOccupation: "Skilled Manual Labour (Tailoring, Hairdressing etc)",
      yearOfMarriage: 2005,
      numberOfChildren: 4,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: " 6012545418",
      accountName: "ALOKO MERCY KIKELOMO",
      bankName: "KEYSTONE BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-11 00:00:00.000"),
      oneOrTwo: 1),
  Widow(
      id: "ANE000828",
      fullName: "Oginni  F Kemi",
      dob: DateTime.parse("1983-01-16 00:00:00.000"),
      state: "Ondo",
      homeTown: "Ikare Akoko",
      address: "Igoba Akure",
      lga: "Akoko North East",
      occupation:
          "Professional/technical/managerial (Lawyer, Manager, Engineer etc.)",
      employmentStatus: "Unemployed",
      phoneNumber: "07031075053",
      husbandName: "Oginni Omotayo",
      husbandBereavementDate: "26 October, 2016",
      husbandOccupation: "Sales and Services (Trading)",
      yearOfMarriage: 2007,
      numberOfChildren: 2,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 1",
      accountNumber: "3010130246",
      accountName: "Omotunwase  Febisola   Kemi",
      bankName: "First Bank",
      ngoMembership: " NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-23 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000607",
      fullName: "SALAU BIKEMI FATIMOH",
      dob: DateTime.parse("1965-01-28 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "MA/16B ISHAKUNMI STREET IKARE AKOKO",
      lga: "Akoko South East",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07031090502",
      husbandName: "SALAU MUYIWA JIMOH",
      husbandBereavementDate: "11 September, 2008",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1990,
      numberOfChildren: 4,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: null,
      accountName: null,
      bankName: null,
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-25 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000487",
      fullName: "AREMU SILIAT",
      dob: DateTime.parse("1958-01-23 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "A/61 ILEPA IKARE",
      lga: "Akoko North East",
      occupation: "Agriculture (Farming, Poultry etc.)",
      employmentStatus: "Unemployed",
      phoneNumber: "07031122816",
      husbandName: "AREMU YUSUF",
      husbandBereavementDate: "21 December, 2009",
      husbandOccupation: "Clerical (Administrative, secretarial etc.)",
      yearOfMarriage: 1977,
      numberOfChildren: 5,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 4",
      accountNumber: "3076967505",
      accountName: "AREMU ABUBAKAR SOLA",
      bankName: "FIRST BANK",
      ngoMembership: " NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-17 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000333",
      fullName: "EUNICE EKUNDAYO OGUNTUASE",
      dob: DateTime.parse("1937-01-08 00:00:00.000"),
      state: "Ondo",
      homeTown: "IKARE AKOKO",
      address: "APOSTOLIC CHURCH ROAD, ILEPA IKARE",
      lga: "Owo",
      occupation: "Sales and Services (Trading)",
      employmentStatus: "Self Employed",
      phoneNumber: "07031232550",
      husbandName: "JULIUS FOLORUNSHO OGUNTUASE",
      husbandBereavementDate: "06 February, 1997",
      husbandOccupation: "Sales and Services (Trading)",
      yearOfMarriage: 1954,
      numberOfChildren: 4,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 3",
      accountNumber: "1910189143",
      accountName: "OGUNTUASE EUNICE EKUNDAYO",
      bankName: "HERITAGE BANK",
      ngoMembership: "NO",
      ngoName: null,
      receivedBy: "SELF",
      registrationDate: DateTime.parse("2020-01-12 00:00:00.000"),
      oneOrTwo: null),
  Widow(
      id: "ANE000054",
      fullName: "Grace Nathaniel",
      dob: DateTime.parse("1944-01-27 00:00:00.000"),
      state: "Ondo",
      homeTown: "Ikare",
      address: "7/04 Iku Street",
      lga: "Akoko North East",
      occupation: "Agriculture (Farming, Poultry etc.)",
      employmentStatus: "Self Employed",
      phoneNumber: "07031364396",
      husbandName: "Nathaniel Aliu",
      husbandBereavementDate: "27 June, 2005",
      husbandOccupation: "Agriculture (Farming, Poultry etc.)",
      yearOfMarriage: 1966,
      numberOfChildren: 3,
      senatorialZone: "Ondo North Senatorial District",
      categoryBasedOnNeeds: "Level 4",
      accountNumber: null,
      accountName: null,
      bankName: null,
      ngoMembership: " NO",
      ngoName: null,
      receivedBy: null,
      registrationDate: DateTime.parse("2020-01-30 00:00:00.000"),
      oneOrTwo: null),
];
