class ChildrenModel {
  ChildrenModel({
    this.RegistrationDate,
    this.SenatorialDistrict,
    this.childrenNumber,
    this.Employment,
    this.Age,
    this.PhoneNumber,
    this.LGA,
    this.NGO,
    this.Name,
    this.ImageUrl,
  });
  String? ImageUrl;
  String? Name;
  String? PhoneNumber;
  int? Age;
  String? Employment;
  String? NGO;
  String? LGA;
  int? childrenNumber;
  String? SenatorialDistrict;
  String? RegistrationDate;

  static List<ChildrenModel> databaseDemos = [
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Mercy',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg2.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 45,
        childrenNumber: 6,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg3.png',
        LGA: 'Ondo South West',
        Name: 'Pete Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg4.png',
        LGA: 'Ondo South West',
        Name: 'lolo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 55,
        childrenNumber: 5,
        Employment: 'Employed',
        ImageUrl: 'assets/databaseimg5.png',
        LGA: 'Ondo North West',
        Name: 'Dami Lorem',
        NGO: 'Peace',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo North West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg6.png',
        LGA: 'Ondo South West',
        Name: 'Dolapo Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 68,
        childrenNumber: 6,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg7.png',
        LGA: 'Ondo South West',
        Name: 'marv Lorem',
        NGO: 'Love',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 25,
        childrenNumber: 8,
        Employment: 'employed',
        ImageUrl: 'assets/databaseimg8.png',
        LGA: 'Ondo South Central',
        Name: 'Dolapo Lorem',
        NGO: 'Faith',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South West'),
    ChildrenModel(
        Age: 64,
        childrenNumber: 8,
        Employment: 'Unmployed',
        ImageUrl: 'assets/databaseimg1.png',
        LGA: 'Ondo South West',
        Name: 'Maku Lorem',
        NGO: 'Hope',
        PhoneNumber: '08035112356',
        RegistrationDate: '12/12/22',
        SenatorialDistrict: 'Ondo South East'),
  ];

}
